config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :products do
    collection {get :name_autocomplete}
  end

  root to: "home#index"

  resources :categories do
    resources :products
  end

  resources :home do
    collection {post :filter_product}
    collection {post :search_product}
  end

  resources :admin

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :category_products
  has_many :products ,  :through => :category_products

  validates :name, :presence => true
  validates :description, :presence => true

  # default ordered
  scope :ordered, -> { order(:name) }
end

app/models/category_product.rb
class CategoryProduct < ActiveRecord::Base
  belongs_to :category
  belongs_to :product
end

app/models/filter_product.rb
class FilterProduct
  include ActiveModel::Model
  attr_accessor :tags, :order, :key_search

  extended Product

  def initialize(attributes={})
    super
    @tags = (@tags ? @tags.reject(&:blank?).map(&:to_i) : [])
    @order ||= nil
    @key_search ||= nil
  end

  def filtered_products
    Product.ordered(@order).tag_filtered(@tags).name_filtered(key_search).active
  end

end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :category_products
  has_many :categories ,  :through => :category_products

  has_many :product_tags
  has_many :tags, :through => :product_tags

  has_many :product_images

  validates :name, :presence => true
  validates :description, :presence => true

  validates :weight, :numericality => true
  validates :price, :numericality => true
  validates :cost_price, :numericality => true, :allow_blank => true


  # All active products
  scope :active, -> { where(:active => true) }

  # All featured products
  scope :featured, -> {where(:featured => true)}

  # default ordered
  scope :ordered, -> (key=:name, direction=:asc) { order(key=>direction) unless key.blank?}

  # filter by name
  scope :name_filtered, -> (key=nil) { where( "products.name like ?", "%#{key}%") unless key.blank?}

  # default filtered
  scope :tag_filtered, -> (tags=nil) { joins(:tags).where(:tags => { :id => tags }).uniq unless tags.blank?}

  # get product tags
  #
  # @return String
  def tags_name
    tags.pluck(:name).join(", ")
  end
end

app/models/product_image.rb
class ProductImage < ActiveRecord::Base
  belongs_to :product
end

app/models/product_tag.rb
class ProductTag < ActiveRecord::Base
  belongs_to :product
  belongs_to :tag
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :product_tags
  has_many :products, through: :product_tags
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :rememberable, :trackable, :validatable
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_user!

  def index

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  def after_sign_in_path_for(resource)
    root_path
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!

  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_path, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to categories_path, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :description)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :init_products, :except => [:filter_product, :search_product]
  before_action :init_tags

  def index

  end

  def filter_product
    init_for_filter
    respond_to do |format|
      format.js
    end
  end

  def search_product
    init_for_filter
    respond_to do |format|
      format.js
    end
  end

  private
  def init_products
    @products = Product.active
    @filter = FilterProduct.new
  end

  def init_tags
    @tags = Tag.all
  end

  def init_for_filter
    get_product_filtered
    @filter = FilterProduct.new(get_product_filtered)
    @products = @filter.filtered_products
  end

  def get_product_filtered
    params.require(:filter_product)
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index,:show]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to products_path, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to products_path, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def name_autocomplete
    @filter = FilterProduct.new(key_search: params[:query])
    @products = @filter.filtered_products

    render :json => {suggestions: @products.collect{|product| {value: product.name, data: product.name}}}
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description)
    end

    def search_key_name
      params.require(:query)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/_admin_menu.html.haml
- if user_signed_in?
  = link_to('Product', products_path)
  |
  = link_to('Categories', categories_path)
  |
  = link_to('Logout', destroy_user_session_path, :method => 'delete')
- else
  = link_to("Sign in", new_user_session_path)

app/views/admin/index.html.haml
.links
  = link_to('Product', products_path)
  |
  = link_to('Categories', categories_path)
  |
  = link_to('Logout', destroy_user_session_path, :method => 'delete')

app/views/categories/_form.html.haml
= form_for(@category) do |f|
  - if @category.errors.any?
    %div#error_explanation
      %h2
        = pluralize(@category.errors.count, "error") +  "prohibited this todo_list from being saved:"

      %ul
        - @category.errors.full_messages.each do |message|
          %li
            = message
    %div

  %div.field
    = f.label :name
    %br
    = f.text_field :name
  %div.field
    = f.label :description
    %br
    = f.text_area :description

  %div.actions
    = f.submit

app/views/categories/edit.html.haml
%h1.todo_list_title Editing Category

.forms
  = render 'form'

.links
  = link_to 'Cancel', category_path

app/views/categories/index.html.haml
- @categories.each do |category|
  .index_row.clearfix
    %h2.todo_list_title
      = link_to category.name, category_path(category)
    %p.todo_list_sub_title
      = category.description
    %p
      = link_to "Products", category_products_path(category.id)
.links

  = link_to "New Category", new_category_path()

app/views/categories/new.html.haml
%h1.todo_list_title New Category

.forms
  = render 'form'

.links
  = link_to 'Back', categories_path

app/views/categories/show.html.haml
%h2.product_title
  = @category.name
%p.product_sub_title
  = @category.description

#category_wrapper
  =# render @category.products
  #form
    =# render "products/form"

.links
  = link_to 'Edit', edit_category_path(@category)
  |
  = link_to 'Delte', categories_path(@category), method: :delete, data: {confirm: "Are you sure?"}
  |
  = link_to 'Back', categories_path

app/views/home/_filter.html.haml
.row
  = form_for(@filter, url: filter_product_home_index_path, :remote => true) do |f|
    .large-6.columns
      .row
        .large-4.columns
          %h5 Filter
          .small-4.row
            = f.collection_check_boxes(:tags, @tags, :id, :name ) do |cb|
              = cb.check_box
              = cb.label
              %br

        .large-4.columns
          %h5 Order by
          .small-4.row
            = f.radio_button :order, 'price'
            = f.label "Price"
          .small-4.row
            = f.radio_button :order, 'weight'
            = f.label "Weigh"
      .row.go
        = f.submit "GO"

    .large-6.columns
      .small-8.columns
        = f.text_field :key_search, :class=>"autocomplete"
      .row.search
        = f.submit "Search"

app/views/home/filter_product.js.haml
$('.product_content').replaceWith("#{escape_javascript render 'products/product_list'}");

app/views/home/index.html.haml
= render "filter"


= render "products/product_list"




.links

app/views/layouts/application.html.haml
<!DOCTYPE html>
%html
%head
%title Keley
= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
= javascript_include_tag 'application', 'data-turbolinks-track' => true
%link{:href => "http://fonts.googleapis.com/css?family=Lato:300,400,700", :rel => "stylesheet", :type => "text/css"}
%link{:href => "//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css", :rel => "stylesheet"}
= csrf_meta_tags

%body
  .container
    = render "admin/admin_menu"
  .container
    - if notice
      .notice
        = notice
    - elsif alert
      .alert
        = alert
    = yield

app/views/products/_form.html.haml
= form_for(@product) do |f|
  - if @product.errors.any?
    %div#error_explanation
      %h2
        = pluralize(@product.errors.count, "error") +  "prohibited this todo_list from being saved:"

      %ul
        - @product.errors.full_messages.each do |message|
          %li
            = message
    %div

  %div.field
    = f.label :name
    %br
    = f.text_field :name
  %div.field
    = f.label :description
    %br
    = f.text_area :description

  %div.field
    = f.label :price
    %br
    = f.number_field :price

  %div.field
    = f.label :weight
    %br
    = f.number_field :weight

  %div.actions
    = f.submit

app/views/products/_product_list.html.haml
.product_content
  - @products.each do |product|
    .panel.callout
      .row
        .large-2.columns.small-3
          = image_tag("produit.jpg")
        .large-8.columns
          .row
            %h2.product_title
              %h3
                = product.name
          .row
            %h5.subheader
              = product.price
              Euros
              |
              = product.weight
              Kg
          .row
            = product.tags_name
        .large-2.columns.small-3
          = link_to "More details", product

app/views/products/edit.html.haml
%h1 Editing Product

= render 'form'

= link_to 'Back', products_path

app/views/products/index.html.haml
= render "product_list"

.links
  = link_to "New Product", new_product_path

app/views/products/new.html.haml
%h1 New Product

= render 'form'

= link_to 'Back', products_path

app/views/products/show.html.haml
= link_to 'Edit', edit_product_path(@product)
= link_to 'Back', products_path